services:
    app:
      image: node:lts
      working_dir: /app
      ports: 
      - '3000:3000'
      volumes:
        - ./:/app
      command: bash -c "cd nextjs-practice-02 && npm install && /bin/bash"
      tty: true
      stdin_open: true